-- Migration 001 — initial schema for broad-state Phase 7.
-- Translates from hai/docs/state_model_v1.md. Do not edit this file;
-- future changes land as new migrations (002_*.sql, 003_*.sql, ...).
--
-- Layer conventions (per state_model_v1.md §2):
--   - Raw evidence:   source-shaped, immutable after ingest, append-only with
--                     supersedes_<id> pointers for corrections.
--   - Accepted state: runtime's committed synthesis, UPSERT + corrected_at.
--   - Agent/review:   append-only. Multiple same-day rows retained.
--
-- Every row carries two-dimension provenance: source (fact origin) +
-- ingest_actor (what transported it).
--
-- Timestamps: TEXT in ISO-8601. SQLite has no native TIMESTAMP type;
-- storing ISO strings keeps lexicographic ordering == chronological.


-- ============================================================================
-- RAW EVIDENCE LAYER
-- ============================================================================

-- Per-day Garmin export row. Carries every column from daily_summary_export.csv.
CREATE TABLE source_daily_garmin (
    as_of_date                              TEXT    NOT NULL,  -- civil date, user-local
    user_id                                 TEXT    NOT NULL,
    export_batch_id                         TEXT    NOT NULL,  -- which csv ingest run
    csv_row_index                           INTEGER NOT NULL,  -- row within that csv

    source                                  TEXT    NOT NULL,  -- 'garmin'
    ingest_actor                            TEXT    NOT NULL,  -- 'garmin_csv_adapter' | ...
    ingested_at                             TEXT    NOT NULL,
    supersedes_export_batch_id              TEXT,

    -- Activity + energy
    steps                                   INTEGER,
    distance_m                              REAL,
    active_kcal                             REAL,
    total_kcal                              REAL,
    moderate_intensity_min                  INTEGER,
    vigorous_intensity_min                  INTEGER,
    floors_ascended_m                       REAL,
    avg_environment_altitude_m              REAL,

    -- Heart rate
    resting_hr                              REAL,
    min_hr_day                              REAL,
    max_hr_day                              REAL,

    -- Sleep
    sleep_deep_sec                          INTEGER,
    sleep_light_sec                         INTEGER,
    sleep_rem_sec                           INTEGER,
    sleep_awake_sec                         INTEGER,
    avg_sleep_respiration                   REAL,
    avg_sleep_stress                        REAL,
    awake_count                             INTEGER,
    sleep_score_overall                     INTEGER,
    sleep_score_quality                     INTEGER,
    sleep_score_duration                    INTEGER,
    sleep_score_recovery                    INTEGER,

    -- Stress + body battery
    all_day_stress                          INTEGER,
    body_battery                            INTEGER,

    -- Training readiness
    training_readiness_level                TEXT,
    training_recovery_time_hours            REAL,
    training_readiness_sleep_pct            REAL,
    training_readiness_hrv_pct              REAL,
    training_readiness_stress_pct           REAL,
    training_readiness_sleep_history_pct    REAL,
    training_readiness_load_pct             REAL,
    training_readiness_hrv_weekly_avg       REAL,
    training_readiness_valid_sleep          INTEGER,

    -- Load
    acute_load                              REAL,
    chronic_load                            REAL,
    acwr_status                             TEXT,
    acwr_status_feedback                    TEXT,
    training_status                         TEXT,
    training_status_feedback                TEXT,

    -- Health baselines (HRV / HR / SpO2 / skin temp / respiration)
    health_hrv_value                        REAL,
    health_hrv_status                       TEXT,
    health_hrv_baseline_low                 REAL,
    health_hrv_baseline_high                REAL,
    health_hr_value                         REAL,
    health_hr_status                        TEXT,
    health_hr_baseline_low                  REAL,
    health_hr_baseline_high                 REAL,
    health_spo2_value                       REAL,
    health_spo2_status                      TEXT,
    health_spo2_baseline_low                REAL,
    health_spo2_baseline_high               REAL,
    health_skin_temp_c_value                REAL,
    health_skin_temp_c_status               TEXT,
    health_skin_temp_c_baseline_low         REAL,
    health_skin_temp_c_baseline_high        REAL,
    health_respiration_value                REAL,
    health_respiration_status               TEXT,
    health_respiration_baseline_low         REAL,
    health_respiration_baseline_high        REAL,

    PRIMARY KEY (as_of_date, user_id, export_batch_id)
);
CREATE INDEX idx_source_daily_garmin_as_of_date ON source_daily_garmin (as_of_date, user_id);


-- Per-activity running. DECLARED BUT EMPTY IN V1. Populated only when
-- activities_export.csv (or a replacement source) is re-synced.
CREATE TABLE running_session (
    session_id                  TEXT    PRIMARY KEY,
    user_id                     TEXT    NOT NULL,
    as_of_date                  TEXT    NOT NULL,
    started_at                  TEXT,
    duration_s                  REAL,
    distance_m                  REAL,
    avg_hr                      INTEGER,

    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    submission_id               TEXT,
    export_batch_id             TEXT,
    ingested_at                 TEXT    NOT NULL,
    supersedes_session_id       TEXT
);
CREATE INDEX idx_running_session_date ON running_session (as_of_date, user_id);


-- Resistance-training session header (raw, user-reported).
CREATE TABLE gym_session (
    session_id                  TEXT    PRIMARY KEY,
    user_id                     TEXT    NOT NULL,
    as_of_date                  TEXT    NOT NULL,
    session_name                TEXT,
    notes                       TEXT,

    source                      TEXT    NOT NULL,  -- 'user_manual'
    ingest_actor                TEXT    NOT NULL,
    submission_id               TEXT,
    ingested_at                 TEXT    NOT NULL,
    supersedes_session_id       TEXT
);
CREATE INDEX idx_gym_session_date ON gym_session (as_of_date, user_id);


-- Individual set within a gym session. Append-only; corrections insert a new
-- row with supersedes_set_id set.
CREATE TABLE gym_set (
    set_id                      TEXT    PRIMARY KEY,
    session_id                  TEXT    NOT NULL REFERENCES gym_session (session_id),
    set_number                  INTEGER NOT NULL,
    exercise_name               TEXT    NOT NULL,
    weight_kg                   REAL,
    reps                        INTEGER,
    rpe                         REAL,

    ingested_at                 TEXT    NOT NULL,
    supersedes_set_id           TEXT
);
CREATE INDEX idx_gym_set_session ON gym_set (session_id, set_number);


-- Raw nutrition intake (user-reported).
CREATE TABLE nutrition_intake_raw (
    submission_id               TEXT    PRIMARY KEY,
    user_id                     TEXT    NOT NULL,
    as_of_date                  TEXT    NOT NULL,

    calories                    REAL,
    protein_g                   REAL,
    carbs_g                     REAL,
    fat_g                       REAL,
    hydration_l                 REAL,
    meals_count                 INTEGER,

    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    ingested_at                 TEXT    NOT NULL,
    supersedes_submission_id    TEXT
);
CREATE INDEX idx_nutrition_intake_raw_date ON nutrition_intake_raw (as_of_date, user_id);


-- Raw manual subjective stress score (user-reported).
CREATE TABLE stress_manual_raw (
    submission_id               TEXT    PRIMARY KEY,
    user_id                     TEXT    NOT NULL,
    as_of_date                  TEXT    NOT NULL,

    score                       INTEGER NOT NULL,  -- 1..5
    tags                        TEXT,              -- comma-separated or JSON

    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    ingested_at                 TEXT    NOT NULL,
    supersedes_submission_id    TEXT
);
CREATE INDEX idx_stress_manual_raw_date ON stress_manual_raw (as_of_date, user_id);


-- Free-text context note. Append-only; corrections insert a new row with
-- supersedes_note_id set. No schema on the body.
CREATE TABLE context_note (
    note_id                     TEXT    PRIMARY KEY,
    user_id                     TEXT    NOT NULL,
    as_of_date                  TEXT    NOT NULL,
    recorded_at                 TEXT    NOT NULL,
    text                        TEXT    NOT NULL,
    tags                        TEXT,

    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    ingested_at                 TEXT    NOT NULL,
    supersedes_note_id          TEXT
);
CREATE INDEX idx_context_note_date ON context_note (as_of_date, user_id);


-- ============================================================================
-- ACCEPTED CANONICAL STATE LAYER
-- ============================================================================

-- Accepted recovery state — daily grain. Derived from source_daily_garmin +
-- stress_manual_raw. Sleep and acute/chronic load stay as fields here per
-- state_model_v1.md §0 / §8.
CREATE TABLE accepted_recovery_state_daily (
    as_of_date                  TEXT    NOT NULL,
    user_id                     TEXT    NOT NULL,

    sleep_hours                 REAL,   -- derived from deep + light + rem
    resting_hr                  REAL,
    hrv_ms                      REAL,
    all_day_stress              INTEGER,
    manual_stress_score         INTEGER,
    acute_load                  REAL,
    chronic_load                REAL,
    acwr_ratio                  REAL,
    training_readiness_pct      REAL,
    body_battery_end_of_day     INTEGER,

    derived_from                TEXT    NOT NULL,  -- JSON array of source row refs
    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    projected_at                TEXT    NOT NULL,
    corrected_at                TEXT,

    PRIMARY KEY (as_of_date, user_id)
);


-- Accepted running state — daily grain. v1 derives from source_daily_garmin
-- with derivation_path='garmin_daily'; flips to 'running_sessions' when per-
-- activity data arrives.
CREATE TABLE accepted_running_state_daily (
    as_of_date                  TEXT    NOT NULL,
    user_id                     TEXT    NOT NULL,

    total_distance_m            REAL,
    total_duration_s            REAL,
    moderate_intensity_min      INTEGER,
    vigorous_intensity_min      INTEGER,
    session_count               INTEGER,   -- NULL when derivation_path='garmin_daily'
    derivation_path             TEXT    NOT NULL CHECK (derivation_path IN ('garmin_daily', 'running_sessions')),

    derived_from                TEXT    NOT NULL,
    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    projected_at                TEXT    NOT NULL,
    corrected_at                TEXT,

    PRIMARY KEY (as_of_date, user_id)
);


-- Accepted resistance-training state — daily grain. Derived from gym_session
-- + gym_set rows.
CREATE TABLE accepted_resistance_training_state_daily (
    as_of_date                  TEXT    NOT NULL,
    user_id                     TEXT    NOT NULL,

    session_count               INTEGER NOT NULL,
    total_sets                  INTEGER NOT NULL,
    total_volume_kg_reps        REAL,
    exercises                   TEXT,        -- JSON array of exercise names

    derived_from                TEXT    NOT NULL,
    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    projected_at                TEXT    NOT NULL,
    corrected_at                TEXT,

    PRIMARY KEY (as_of_date, user_id)
);


-- Accepted nutrition state — daily grain. Normally a pass-through of the
-- latest nutrition_intake_raw row for (as_of_date, user_id).
CREATE TABLE accepted_nutrition_state_daily (
    as_of_date                  TEXT    NOT NULL,
    user_id                     TEXT    NOT NULL,

    calories                    REAL,
    protein_g                   REAL,
    carbs_g                     REAL,
    fat_g                       REAL,
    hydration_l                 REAL,
    meals_count                 INTEGER,

    derived_from                TEXT    NOT NULL,
    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    projected_at                TEXT    NOT NULL,
    corrected_at                TEXT,

    PRIMARY KEY (as_of_date, user_id)
);


-- Goal — multiple concurrent allowed, optionally domain-scoped.
-- Active goals are rows where ended_on IS NULL.
CREATE TABLE goal (
    goal_id                     TEXT    PRIMARY KEY,
    user_id                     TEXT    NOT NULL,
    label                       TEXT    NOT NULL,
    domain                      TEXT,              -- 'resistance_training' | 'running' | 'nutrition' | 'recovery' | NULL
    started_on                  TEXT    NOT NULL,  -- civil date
    ended_on                    TEXT,
    created_at                  TEXT    NOT NULL,

    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL
);
CREATE INDEX idx_goal_active ON goal (user_id, ended_on);


-- ============================================================================
-- RECOMMENDATION + REVIEW LAYER
-- ============================================================================

-- Training recommendations produced by the agent. Append-only; multiple
-- same-day rows (suffix _01, _02) retained.
CREATE TABLE recommendation_log (
    recommendation_id           TEXT    PRIMARY KEY,
    user_id                     TEXT    NOT NULL,
    for_date                    TEXT    NOT NULL,
    issued_at                   TEXT    NOT NULL,

    action                      TEXT    NOT NULL,
    confidence                  TEXT    NOT NULL,
    bounded                     INTEGER NOT NULL CHECK (bounded IN (0, 1)),
    payload_json                TEXT    NOT NULL,       -- full TrainingRecommendation JSON

    jsonl_offset                INTEGER,                -- byte offset into source jsonl, if known
    source                      TEXT    NOT NULL,       -- 'claude_agent_v1' etc
    ingest_actor                TEXT    NOT NULL,
    agent_version               TEXT,
    produced_at                 TEXT,
    validated_at                TEXT    NOT NULL,
    projected_at                TEXT    NOT NULL
);
CREATE INDEX idx_recommendation_log_for_date ON recommendation_log (for_date, user_id, issued_at);


-- Scheduled review event for a recommendation.
CREATE TABLE review_event (
    review_event_id             TEXT    PRIMARY KEY,
    recommendation_id           TEXT    NOT NULL REFERENCES recommendation_log (recommendation_id),
    user_id                     TEXT    NOT NULL,
    review_at                   TEXT    NOT NULL,
    review_question             TEXT    NOT NULL,

    projected_at                TEXT    NOT NULL
);
CREATE INDEX idx_review_event_user ON review_event (user_id, review_at);


-- User-reported outcome against a review event. Append-only.
CREATE TABLE review_outcome (
    outcome_id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    review_event_id             TEXT    NOT NULL REFERENCES review_event (review_event_id),
    recommendation_id           TEXT    NOT NULL REFERENCES recommendation_log (recommendation_id),
    user_id                     TEXT    NOT NULL,
    recorded_at                 TEXT    NOT NULL,

    followed_recommendation     INTEGER NOT NULL CHECK (followed_recommendation IN (0, 1)),
    self_reported_improvement   INTEGER CHECK (self_reported_improvement IN (0, 1)),  -- NULL allowed = unknown
    free_text                   TEXT,

    jsonl_offset                INTEGER,
    source                      TEXT    NOT NULL,
    ingest_actor                TEXT    NOT NULL,
    projected_at                TEXT    NOT NULL
);
CREATE INDEX idx_review_outcome_event ON review_outcome (review_event_id);
