"""Local SQLite state store — schema, migrations, and connection management.

Phase 7A.1 substrate. Projector, dual-write, read CLIs, and snapshot logic
arrive in later phases. This module is not imported by any subcommand beyond
``hai state init`` and ``hai state migrate`` until 7A.2.
"""

from health_agent_infra.core.state.projector import (
    ReprojectBaseDirError,
    aggregate_activities_to_daily_rollup,
    delete_canonical_plan_cascade,
    latest_nutrition_submission_id,
    link_proposal_to_plan,
    mark_plan_superseded,
    merge_manual_stress_into_accepted_recovery,  # legacy alias
    merge_manual_stress_into_accepted_stress,
    project_accepted_nutrition_state_daily,
    project_accepted_recovery_state_daily,
    project_accepted_resistance_training_state_daily,
    project_accepted_running_state_daily,
    project_accepted_sleep_state_daily,
    project_accepted_stress_state_daily,
    project_activity,
    project_bounded_recommendation,
    project_context_note,
    project_daily_plan,
    project_exercise_taxonomy_entry,
    project_gym_session,
    project_gym_set,
    project_manual_readiness_raw,
    project_nutrition_intake_raw,
    project_planned_recommendation,
    ProposalReplaceRequired,
    project_proposal,
    project_recommendation,
    project_review_event,
    project_review_outcome,
    project_source_daily_garmin,
    project_stress_manual_raw,
    project_x_rule_firing,
    read_activities_for_date,
    read_activities_range,
    read_canonical_plan,
    read_latest_manual_readiness,
    read_proposals_for_plan_key,
    reproject_from_jsonl,
)
from health_agent_infra.core.state.snapshot import (
    available_domains,
    build_snapshot,
    read_domain,
)
from health_agent_infra.core.state.store import (
    DEFAULT_DB_PATH,
    apply_pending_migrations,
    current_schema_version,
    initialize_database,
    migration_004_dry_run_diff,
    open_connection,
    resolve_db_path,
)
from health_agent_infra.core.state.sync_log import (
    begin_sync,
    complete_sync,
    fail_sync,
    latest_successful_sync_per_source,
    sync_run,
)
from health_agent_infra.core.state.runtime_event_log import (
    begin_event,
    command_summary,
    complete_event,
    fail_event,
    recent_events,
    runtime_event,
)

__all__ = [
    "DEFAULT_DB_PATH",
    "ReprojectBaseDirError",
    "aggregate_activities_to_daily_rollup",
    "apply_pending_migrations",
    "available_domains",
    "begin_event",
    "begin_sync",
    "build_snapshot",
    "command_summary",
    "complete_event",
    "complete_sync",
    "current_schema_version",
    "delete_canonical_plan_cascade",
    "fail_event",
    "fail_sync",
    "initialize_database",
    "latest_nutrition_submission_id",
    "latest_successful_sync_per_source",
    "link_proposal_to_plan",
    "mark_plan_superseded",
    "merge_manual_stress_into_accepted_recovery",
    "merge_manual_stress_into_accepted_stress",
    "migration_004_dry_run_diff",
    "open_connection",
    "project_accepted_nutrition_state_daily",
    "project_accepted_recovery_state_daily",
    "project_accepted_resistance_training_state_daily",
    "project_accepted_running_state_daily",
    "project_accepted_sleep_state_daily",
    "project_accepted_stress_state_daily",
    "project_activity",
    "project_bounded_recommendation",
    "project_context_note",
    "project_daily_plan",
    "project_exercise_taxonomy_entry",
    "project_gym_session",
    "project_gym_set",
    "project_manual_readiness_raw",
    "project_nutrition_intake_raw",
    "project_planned_recommendation",
    "ProposalReplaceRequired",
    "project_proposal",
    "project_recommendation",
    "project_review_event",
    "project_review_outcome",
    "project_source_daily_garmin",
    "project_stress_manual_raw",
    "project_x_rule_firing",
    "read_activities_for_date",
    "read_activities_range",
    "read_canonical_plan",
    "read_domain",
    "read_latest_manual_readiness",
    "read_proposals_for_plan_key",
    "recent_events",
    "reproject_from_jsonl",
    "resolve_db_path",
    "runtime_event",
    "sync_run",
]
