"""Local SQLite state store — schema, migrations, and connection management.

Phase 7A.1 substrate. Projector, dual-write, read CLIs, and snapshot logic
arrive in later phases. This module is not imported by any subcommand beyond
``hai state init`` and ``hai state migrate`` until 7A.2.
"""

from health_agent_infra.core.state.projector import (
    ReprojectBaseDirError,
    delete_canonical_plan_cascade,
    latest_nutrition_submission_id,
    link_proposal_to_plan,
    mark_plan_superseded,
    merge_manual_stress_into_accepted_recovery,  # legacy alias
    merge_manual_stress_into_accepted_stress,
    project_accepted_nutrition_state_daily,
    project_accepted_recovery_state_daily,
    project_accepted_resistance_training_state_daily,
    project_accepted_running_state_daily,
    project_accepted_sleep_state_daily,
    project_accepted_stress_state_daily,
    project_bounded_recommendation,
    project_context_note,
    project_daily_plan,
    project_exercise_taxonomy_entry,
    project_gym_session,
    project_gym_set,
    project_nutrition_intake_raw,
    project_proposal,
    project_recommendation,
    project_review_event,
    project_review_outcome,
    project_source_daily_garmin,
    project_stress_manual_raw,
    project_x_rule_firing,
    read_canonical_plan,
    read_proposals_for_plan_key,
    reproject_from_jsonl,
)
from health_agent_infra.core.state.snapshot import (
    available_domains,
    build_snapshot,
    read_domain,
)
from health_agent_infra.core.state.store import (
    DEFAULT_DB_PATH,
    apply_pending_migrations,
    current_schema_version,
    initialize_database,
    migration_004_dry_run_diff,
    open_connection,
    resolve_db_path,
)

__all__ = [
    "DEFAULT_DB_PATH",
    "ReprojectBaseDirError",
    "apply_pending_migrations",
    "available_domains",
    "build_snapshot",
    "current_schema_version",
    "delete_canonical_plan_cascade",
    "initialize_database",
    "latest_nutrition_submission_id",
    "link_proposal_to_plan",
    "mark_plan_superseded",
    "merge_manual_stress_into_accepted_recovery",
    "merge_manual_stress_into_accepted_stress",
    "migration_004_dry_run_diff",
    "open_connection",
    "project_accepted_nutrition_state_daily",
    "project_accepted_recovery_state_daily",
    "project_accepted_resistance_training_state_daily",
    "project_accepted_running_state_daily",
    "project_accepted_sleep_state_daily",
    "project_accepted_stress_state_daily",
    "project_bounded_recommendation",
    "project_context_note",
    "project_daily_plan",
    "project_exercise_taxonomy_entry",
    "project_gym_session",
    "project_gym_set",
    "project_nutrition_intake_raw",
    "project_proposal",
    "project_recommendation",
    "project_review_event",
    "project_review_outcome",
    "project_source_daily_garmin",
    "project_stress_manual_raw",
    "project_x_rule_firing",
    "read_canonical_plan",
    "read_domain",
    "read_proposals_for_plan_key",
    "reproject_from_jsonl",
    "resolve_db_path",
]
